name: basic_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: GothicA1
      fonts:
        - asset: assets/fonts/gothic/GothicA1-Black.ttf
        - asset: assets/fonts/gothic/GothicA1-Bold.ttf
        - asset: assets/fonts/gothic/GothicA1-ExtraBold.ttf
        - asset: assets/fonts/gothic/GothicA1-Light.ttf
        - asset: assets/fonts/gothic/GothicA1-Medium.ttf
        - asset: assets/fonts/gothic/GothicA1-Regular.ttf
        - asset: assets/fonts/gothic/GothicA1-Thin.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100

  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
